## Тема лекции: Введение в numpy и pytorch.

В ходе лекции рассмотрим следующие темы:
* Что такое numpy
* Основные операции numpy
* Сравнение numpy операции с python
* В чем преимущество pytorch над numpy
* Основные операции в pytorch
* Что такое граф вычислений в pytorch и зачем он нужен

## Что такое numpy

![types](./pictures/numpy.png)

NumPy - это библиотека Python, используемая для работы с массивами.

Он также имеет функции для работы с
* линейной алгебры
* преобразования Фурье
* матрицами

NumPy был создан в 2005 году Трэвисом Олифантом. Это проект с открытым исходным кодом, и вы можете свободно им пользоваться.



## Зачем мы используем NumPy?

В Python у нас есть list, которые служат для создания массивов, но они медленно обрабатываются.

NumPy стремится предоставить объект массива, который до 50 раз быстрее, чем традиционные списки Python.

Объект массива в NumPy называется ndarray, он предоставляет множество вспомогательных функций, которые упрощают работу с ndarray.

Массивы очень часто используются в науке о данных, где очень важны скорость и ресурсы.

## Почему NumPy быстрее lists?

Массивы NumPy хранятся в одном непрерывном месте в памяти, в отличие от списков, поэтому обращением к ним происходит наиболее эффективно.

Это основная причина, по которой NumPy быстрее списков. Также он оптимизирован для работы с новейшими архитектурами CPU благодаря SIMD инструкциям.

NumPy - это библиотека Python, которая частично написана на Python, но большинство частей, требующих быстрых вычислений, написаны на C или C ++.

![types](./pictures/simd.png)

## Установка и импорт

In [1]:
!pip install numpy

In [2]:
import numpy as np

## Создание numpy массивов

In [6]:
x = np.array([[1, 2, 3], [4, 5, 6]])

In [7]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
x.shape

(2, 3)

In [12]:
x = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]], dtype=np.float32)

In [10]:
x

array([[[1., 2., 3.],
        [4., 5., 6.]],

       [[1., 2., 3.],
        [4., 5., 6.]]], dtype=float32)

In [13]:
x.shape

(2, 2, 3)

In [18]:
np.arange(100).astype(np.float32)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
       65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77.,
       78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90.,
       91., 92., 93., 94., 95., 96., 97., 98., 99.], dtype=float32)

In [19]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.ones(shape=(10, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
x = np.arange(100).reshape(10, 10)

In [25]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [51]:
x.shape

(10, 10)

## Базовые операции

In [26]:
a = np.array( [20,30,40,50] )

In [27]:
a+a

array([ 40,  60,  80, 100])

In [28]:
a**2

array([ 400,  900, 1600, 2500])

In [77]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [32]:
a==a

array([ True,  True,  True,  True])

In [33]:
A = np.array( [[1,1],
                [0,1]] )
B = np.array( [[2,0],
                [3,4]] )

In [34]:
A * B                       # elementwise product

array([[2, 0],
       [0, 4]])

In [35]:
A.dot(B)                    # matrix product

array([[5, 4],
       [3, 4]])

In [85]:
np.linspace(0,np.pi,10)

array([0.        , 0.34906585, 0.6981317 , 1.04719755, 1.3962634 ,
       1.74532925, 2.0943951 , 2.44346095, 2.7925268 , 3.14159265])

In [36]:
x = np.random.randint(0, 32, size=100).reshape(25, 4)
print(x)

[[27 14 20 26]
 [19 22  1  2]
 [25 30 22 27]
 [20 26 16 30]
 [ 2 21 26 17]
 [10 26 20 30]
 [28 15  7 23]
 [31 31 27 23]
 [22  3  5 26]
 [ 9 26 16 31]
 [ 8 25 24  0]
 [ 1 29  4 12]
 [ 2 17 24  7]
 [22 31 27 24]
 [19 16  6 29]
 [ 9 20  4 31]
 [ 1 19 15 19]
 [27 26  8  8]
 [ 8  2 18  8]
 [11 31 30 20]
 [ 9 23  8 23]
 [ 5 23 14 11]
 [28 27 16  8]
 [ 3 20 15  3]
 [21 24 17 28]]


In [37]:
print(x.sum())
print(x.min())
print(x.max())

1770
0
31


In [38]:
x.sum(axis=0)

array([367, 547, 390, 466])

In [39]:
x.sum(axis=1)

array([ 87,  44, 104,  92,  66,  86,  73, 112,  56,  82,  57,  46,  50,
       104,  70,  64,  54,  69,  36,  92,  63,  53,  79,  41,  90])

In [40]:
x.min(axis=1)

array([14,  1, 22, 16,  2, 10,  7, 23,  3,  9,  0,  1,  2, 22,  6,  4,  1,
        8,  2, 11,  8,  5,  8,  3, 17])

In [41]:
x.max(axis=0)

array([31, 31, 30, 31])

In [42]:
x = np.arange(3)

In [43]:
print(np.exp(x))
print(np.sqrt(x))
print(x+x)

[1.         2.71828183 7.3890561 ]
[0.         1.         1.41421356]
[0 2 4]


## Индексация

In [54]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [64]:
a = np.random.randint(0, 100, size=(10000))

In [53]:
a[0,0,0]

51

In [45]:
a[2]

8

In [55]:
a[2:5]

array([ 8, 27, 64])

In [56]:
a[:6:2] = 1000
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729])

In [57]:
a[ : :-1]                                 # reversed a

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000])

In [110]:
for i in a:
     print(i**(1/3.))

9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [ ]:
%timeit f1(x, y)

In [60]:
x = [1,2,3,4]
y = [5,6,7,8]

In [62]:
z = [a*b for a,b in zip(x,y)]

In [63]:
z

[5, 12, 21, 32]

## Почему numpy (кроме того что удобно)

![types](./pictures/dot_product.png)

In [72]:
x = np.random.randint(0, 32, size=(10000))
y = np.random.randint(0, 32, size=(10000))

In [73]:
def f1(x, y):
    return sum(a*b for a,b in zip(x,y))

In [74]:
def f2(x, y):
    return (x * y).sum()

In [75]:
f1(x, y)

241847385

In [76]:
f2(x, y)

2408510

In [70]:
%timeit f1(x, y)

5.28 ms ± 2.49 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [71]:
%timeit f2(x, y)

27.4 µs ± 4.51 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


## Сравнение с pytorch

In [73]:
!pip install torch torchvision

In [77]:
import torch

In [78]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

In [79]:
x_data

tensor([[1, 2],
        [3, 4]])

In [81]:
x_data.shape

torch.Size([2, 2])

In [82]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [85]:
x_ones = torch.ones_like(x_data)
x_rand = torch.rand_like(x_data, dtype=torch.float)

In [84]:
x_rand

tensor([[0.6232, 0.4570],
        [0.0500, 0.3845]])

In [86]:
if torch.cuda.is_available():
    x_rand = x_rand.to('cuda')

In [87]:
x = np.random.randint(0, 32, size=(10000))
y = np.random.randint(0, 32, size=(10000))

In [88]:
x_torch = torch.from_numpy(x)
y_torch = torch.from_numpy(y)

In [89]:
def f3(x,y):
    return torch.sum(x_torch * y_torch)

In [90]:
%timeit f2(x, y)

24.2 µs ± 5.61 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [91]:
%timeit f3(x_torch, y_torch)

24.3 µs ± 6.87 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [72]:
x = torch.ones(5)  # input tensor
y = torch.zeros(3)  # expected output
w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
z = torch.matmul(x, w)+b

![types](./pictures/graph.png)

## Полезные ссылки:
* https://numpy.org/doc/stable/user/quickstart.html
* https://numpy.org/doc/stable/numpy-user.pdf
* https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html
* https://pytorch.org/tutorials/beginner/basics/autogradqs_tutorial.html
* https://pytorch.org/docs/stable/torch.html